#!/usr/bin/python3
import sys


def factorize_number(n):
    for i in range(2, n + 1):
        if n % i == 0:
            return (i, n // i)


def main(input_file):
    with open(input_file, 'r') as file:
        for line in file:
            try:
                n = int(line)
                if n > 1:
                    factors = factorize_number(n)
                    print(f"{n}={factors[0]}*{factors[1]}")
            except ValueError:
                continue


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        sys.exit(1)

    input_file = sys.argv[1]
    main(input_file)
